---
title: "Heatwaves and carbon dioxide enrichment impact invertebrate drift and insect emergence patterns across time in experimental streams"
Year: 2024
Authors: "Hunn, J. G., Orr, J. A., Kelly, A. M., Piggott, J. J., & Matthaei, C. D."
Journal: "Science of The Total Environment"
categories: [Global Change Biology, Multiple Stressors, Freshwater]
doi: "https://doi.org/10.1016/j.scitotenv.2024.173106"
---

Climate change and human land use are considered key threats to freshwater invertebrates. Heatwaves can impact the phenology of insects and population dynamics, yet have been largely ignored in experiments compared to mean temperature changes. Another major anthropogenic stressor driving insect community changes is deposited fine sediment; therefore, effects of key climate-change drivers on invertebrate drift and insect emergence rates may differ between sediment-impacted and non-impacted streams. However, this has never been tested in a realistic outdoor experiment. We investigated the individual and combined effects of two 7-day heatwaves, CO2 enrichment, flow velocity variability (periods of fast and slow), and fine sediment on stream drift and emergence responses, sampled four times during a 7-week experiment in 128 flow-through stream mesocosms. We examined invertebrate drift and insect emergence responses to the four stressors, and used these responses to help explain the benthic invertebrate community responses already assessed (sampled at the end of the experiment). Heatwave 1 strongly increased emergence (dominated by Chironomidae), causing an earlier emergence peak, an effect not repeated during heatwave 2, seven days later. During heatwave 1, emerged chironomids were larger in heated channels, but smaller in heated channels afterwards, suggesting a different effect on body size of short-term heatwaves to previous constant warming experiments. CO2 enrichment reduced drifting EPT and total and Chironomidae emergence on three sampling occasions each. After heatwave 1, total drift and total emergence were strongly reduced by heating in ambient-CO2 channels, whereas no reduction occurred in CO2-enriched channels. During heatwave 2, total drift increased in channels without sediment but not in channels with added sediment. Overall, our findings suggest heatwaves can shift the timing of stream insect emergence, regardless of longer-term mean temperatures. They also show that heatwaves, raised CO2, and fine sediment can modulate each others' effects on drift and emergence dynamics.										
