---
title: "Modelling the potential for local management practices to offset climate change impacts on freshwater macroinvertebrate communities"
Year: 2024
Authors: "Orr, J. A., Bussi, G., Hughes, J. M., Whitehead, P. G., & Jackson, M. C."
Journal: "Freshwater Biology"
categories: [Global Change Biology, Multiple Stressors, Freshwater]
doi: "https://doi.org/10.1111/fwb.14222"
---

A robust understanding of the interactions between global and local anthropogenic stressors is crucial for ecosystem management in the Anthropocene. Manipulative experiments in the lab or in the field can be used to build knowledge about the physiological and ecological effects of stressors, but predicting the combined landscape-scale effects of global stressors such as climate change and local stressors such as land-use change requires a different approach. Here we used water quality and hydrology process-based models of entire river catchments in combination with a large biomonitoring dataset to predict the responses of macroinvertebrate communities under different climate change and land-use change scenarios. Using the River Thames in the United Kingdom as a model system, we predicted changes in water quality (temperature, flow, phosphorus, nitrogen, dissolved oxygen) and subsequent changes in macroinvertebrate communities for two climate change scenarios individually and in combination with intensified agriculture and reduced phosphorus pollution (representing improved wastewater treatment).  Our models predicted that water quality changes associated with climate change may not influence total species richness, but that community composition will shift towards more pollution-tolerant and common taxa based on responses of community indices and taxon-specific responses. We also found that the negative impacts of climate change on water quality (e.g., increased phosphorus concentration, decreased dissolved oxygen concentration) accumulate through the catchment but that local land-use practices influencing phosphorus dynamics can modify this trend. Furthermore, although the intensified agriculture scenario was predicted to have minimal impacts on macroinvertebrate communities (a result potentially related to shifting baselines as the Thames is already heavily polluted), we found that reduced phosphorus pollution due to improved wastewater treatment was able to mostly offset the negative impacts of climate change on macroinvertebrate communities. Our results demonstrate that using process-based models to study networks of interacting stressors at a landscape scale can provide useful insights into the ecological impacts of anthropogenic global change and adds support to the idea that management of local stressors has the potential to mitigate some of the impacts of climate change on ecosystems.