---
title: "Individual and combined impacts of carbon dioxide enrichment, heatwaves, flow velocity variability, and fine sediment deposition on stream invertebrate communities"
Year: 2024
Authors: "Hunn, J. G., Orr, J. A., Kelly, A. M., Piggott, J. J., & Matthaei, C. D."
Journal: "Global Change Biology"
categories: [Global Change Biology, Multiple Stressors, Freshwater]
doi: "http://doi.org/10.1111/gcb.17336"
---

Climate change and land-use change are widely altering freshwater ecosystem functioning and there is an urgent need to understand how these broad stressor categories may interact in future. While much research has focused on mean temperature increases, climate change also involves increasing variability of both water temperature and flow regimes and increasing concentrations of atmospheric CO2, all with potential to alter stream invertebrate communities. Deposited fine sediment is a pervasive land-use stressor with widespread impacts on stream invertebrates. Sedimentation may be managed at the catchment scale; thus, uncovering interactions with these three key climate stressors may assist mitigation of future threats. This is the first experiment to investigate the individual and combined effects of enriched CO2, heatwaves, flow velocity variability, and fine sediment on realistic stream invertebrate communities. Using 128 mesocosms simulating small stony-bottomed streams in a 7-week experiment, we manipulated dissolved CO2 (ambient; enriched), fine sediment (no sediment; 300 g dry sediment), temperature (ambient; two 7-day heatwaves), and flow velocity (constant; variable). All treatments changed community composition. CO2 enrichment reduced abundances of Orthocladiinae and Chironominae and increased Copepoda abundance. Variable flow velocity had only positive effects on invertebrate abundances (7 of 13 common taxa and total abundance), in contrast to previous experiments showing negative impacts of reduced velocity. CO2 was implicated in most stressor interactions found, with CO2 × sediment interactions being most common. Communities forming under enriched CO2 conditions in sediment-impacted mesocosms had ~20% fewer total invertebrates than those with either treatment alone. Copepoda abundances doubled in CO2-enriched mesocosms without sediment, whereas no CO2 effect occurred in mesocosms with sediment. Our findings provide new insights into potential future impacts of climate change and land use in running freshwaters, in particular highlighting the potential for elevated CO2 to interact with fine sediment deposition in unpredictable ways.								
