project:
  type: website
  output-dir: docs


website:
  title: "James Orr"
  navbar:
    left:
      - text: "About"
        href: index.qmd
      - research.qmd
      - publications.qmd
      #- text: "Tools & Resources"
      #  href: apps.qmd
      - href: https://www.jamesorrphoto.com
        text: Photography
        target: _blank
      

format:
  html:
    theme: sandstone
    #mainfont: arial
    fontsize: 0.9rem
    #fontcolor: "#0013d5"
    #linkcolor: "#ff33f0"
    css: styles.css
    toc: false



