---
title: "Towards a unified study of multiple stressors: divisions and common goals across research disciplines"
Year: 2020
Authors: "Orr, J. A., Vinebrooke, R. D., Jackson, M. C., Kroeker, K. J., Kordas, R. L., Mantyka-Pringle, C., ... & Piggott, J. J. "
Journal: "Proceedings of the Royal Society B"
categories: [Global Change Biology, Multiple Stressors, Synthesis]
doi: "https://doi.org/10.1098/rspb.2020.0421"
---

Anthropogenic environmental changes, or ‘stressors’, increasingly threaten biodiversity and ecosystem functioning worldwide. Multiple-stressor research is a rapidly expanding field of science that seeks to understand and ultimately predict the interactions between stressors. Reviews and meta-analyses of the primary scientific literature have largely been specific to either freshwater, marine or terrestrial ecology, or ecotoxicology. In this cross-disciplinary study, we review the state of knowledge within and among these disciplines to highlight commonality and division in multiple-stressor research. Our review goes beyond a description of previous research by using quantitative bibliometric analysis to identify the division between disciplines and link previously disconnected research communities. Towards a unified research framework, we discuss the shared goal of increased realism through both ecological and temporal complexity, with the overarching aim of improving predictive power. In a rapidly changing world, advancing our understanding of the cumulative ecological impacts of multiple stressors is critical for biodiversity conservation and ecosystem management. Identifying and overcoming the barriers to interdisciplinary knowledge exchange is necessary in rising to this challenge. Division between ecosystem types and disciplines is largely a human creation. Species and stressors cross these borders and so should the scientists who study them.
