---
title: "Factors of global change affecting plants act at different levels of the ecological hierarchy"
Year: 2023
Authors: "Rillig, M. C., Lehmann, A., Orr, J. A., & Rongstock, R. "
Journal: "Plant Journal"
categories: [Global Change Biology, Multiple Stressors]
doi: "http://doi.org/10.1111/tpj.16509"
---

Plants and ecosystems worldwide are exposed to a wide range of chemical, physical, and biological factors of global change, many of which act concurrently. As bringing order to the array of factors is required in order to generate an enhanced understanding of simultaneous impacts, classification schemes have been developed. One such classification scheme is dedicated to capturing the different targets of global change factors along the ecological hierarchy. We build on this pioneering work, and refine the conceptual framework in several ways, focusing on plants and terrestrial systems: (i) we more strictly define the target level of the hierarchy, such that every factor typically has just one target level, and not many; (ii) we include effects above the level of the community, that is, there are effects also at the ecosystem scale that cannot be reduced to any level below this; (iii) we introduce the level of the landscape to capture certain land use change effects while abandoning the level below the individual. We discuss how effects can propagate along the levels of the ecological hierarchy, upwards and downwards, presenting opportunities for explaining non-additivity of effects of multiple factors. We hope that this updated conceptual framework will help inform the next generation of plant-focused global change experiments, specifically aimed at non-additivity of effects at the confluence of many factors.										
