---
title: "Winter is coming: Interactions of multiple stressors in winter and implications for the natural world"
Year: 2023
Authors: "Dinh, K. V., Albini, D., Orr, J. A., Macaulay, S. J., Rillig, M. C., Borgå, K., & Jackson, M. C."
Journal: "Global Change Biology"
categories: [Global Change Biology, Multiple Stressors, Synthesis]
doi: "https://doi.org/10.1111/gcb.16956"
---

Winter is a key driver of ecological processes in freshwater, marine and terrestrial ecosystems, particularly in higher latitudes. Species have evolved various adaptive strategies to cope with food limitations and the cold and dark wintertime. However, human-induced climate change and other anthropogenic stressors are impacting organisms in winter in unpredictable ways. In this paper, we show that global change experiments investigating multiple stressors have predominantly been conducted during summer months. However, effects of anthropogenic stressors sometimes differ between winter and other seasons, necessitating comprehensive investigations. Here, we outline a framework for understanding the different effects of anthropogenic stressors in winter compared to other seasons and discuss the primary mechanisms that will alter ecological responses of organisms (microbes, animals and plants). For instance, while the magnitude of some anthropogenic stressors can be greater in winter than in other seasons (e.g. some pollutants), others may alleviate natural winter stress (e.g. warmer temperatures). These changes can have immediate, delayed or carry-over effects on organisms during winter or later seasons. Interactions between stressors may also vary with season. We call for a renewed research direction focusing on multiple stressor effects on winter ecology and evolution to fully understand, and predict, how ecosystems will fare under changing winters. We also argue the importance of incorporating the interactions of anthropogenic stressors with winter into ecological risk assessments, management and conservation efforts.										
