---
title: "The promise of community-driven preprints in ecology and evolution"
Year: 2025
Authors: "Noble, D., Xirocostas, Z., Wu, N., Martinig, A., Almeida, R., Bairos-Novak, K., ... & Lagisz, M."
Journal: "Proceedings of the Royal Society B"
categories: [Synthesis]
doi: "https://doi.org/10.1098/rspb.2024.1487"
---

Publishing preprints is quickly becoming commonplace in ecology and evolutionary biology. Preprints can facilitate the rapid sharing of scientific knowledge establishing precedence and enabling feedback from the research community before peer review. Yet, significant barriers to preprint use exist including language barriers, a lack of understanding about the benefits of preprints and a lack of diversity in the types of research outputs accepted (e.g., reports). Community driven preprint initiatives can allow a research community to come together to break down these barriers to improve equity and coverage of global knowledge. Here, we explore the first preprints uploaded to EcoEvoRxiv, a community-driven preprint server for ecologists and evolutionary biologists, to characterise preprint practices in ecology, evolution and conservation. Our perspective piece highlights some of the unique initiatives that EcoEvoRxiv has taken to break down barriers to scientific publishing by exploring the composition of articles, how gender and career stage influence preprint use, whether preprints are associated with greater open science principles (e.g., code and data sharing), and tracking preprint publication outcomes. Our analysis identifies areas that we still need to improve upon but highlight how community-driven initiatives, such as EcoEvoRxiv, can play a crucial role in shaping publishing practices in biology.