---
title: "Scaling up uncertain predictions to higher levels of organisation tends to underestimate change"
Year: 2021
Authors: "Orr, J. A., Piggott, J. J., Jackson, A. L., & Arnoldi, J. F."
Journal: "Methods in Ecology and Evolution"
categories: [Theory, Methods]
doi: "https://doi.org/10.1111/2041-210X.13621"
---

Uncertainty is an irreducible part of predictive science, causing us to over- or underestimate the magnitude of change that a system of interest will face. In a reductionist approach, we may use predictions at the level of individual system components (e.g. species biomass), and combine them to generate predictions for system-level properties (e.g. ecosystem function). Here we show that this process of scaling up uncertain predictions to higher levels of organisation has a surprising consequence: it tends to systematically underestimate the magnitude of system-level change, an effect whose significance grows with the system's dimensionality. This stems from a geometric observation: in high dimensions there are more ways to be more different, than ways to be more similar. We focus on ecosystem-level predictions generated from the combination of predictions at the species level. In this setting, the ecosystem's relevant dimensionality is a measure of its diversity (and not simply the number of species). We explain why dimensional effects do not play out when predicting change of a single linear aggregate property (e.g. total biomass), yet are revealed when predicting change of nonlinear properties (e.g. absolute biomass change, stability or diversity), and when several properties are considered at once to describe the ecosystem, as in multi-functional ecology. As an application we discuss the consequences of our theory for multiple-stressor research. This empirical field focuses on interactions between stressors, defined as the error made by a prediction based on their observed individual effects. Our geometric approach can be visualised and explored with a web application (https://doi.org/10.5281/zenodo.4611133), and we provide pseudocode outlining how our theory can be applied. Our findings highlight and describe the counter-intuitive effects of scaling up uncertain predictions, effects that can occur in any field of science where a reductionist approach is used to generate predictions.
