---
title: "Mechanisms underpinning nonadditivity of global change factor effects in the plant–soil system"
Year: 2021
Authors: "Rillig, M. C., Lehmann, A., Orr, J. A., & Waldman, W. R. "
Journal: "New Phytologist"
categories: [Global Change Biology, Multiple Stressors]
doi: "https://doi.org/10.1111/nph.17714"
---

Plant–soil systems are key for understanding the effects of factors of global change. Recent work has highlighted the general importance of considering the simultaneous incidence of some factors or stressors. To help mechanistically dissect the possible interactions of such factors, we here propose three broad groups of mechanisms that may generally lead to nonadditivity of responses within a plant–soil system: direct factor interactions (that is one factor directly changing another), within-plant information processing and crosstalk, and effects of factors on groups of soil biota interacting with plants. Interactions are also possible within and across these groups. Factor interactions are very likely to be present in experiments, especially when dealing with an increasing number of factors. Identifying the nature of such interactions will be essential for understanding and predicting global change impacts on plants and soil.							